- Version bump to 10.4.3 (bugfix release):   * Bug 80568 - [gen4] GPU Crash During Google Chrome Operation   * Bug 85367 - [gen4] GPU hang in glmark-es2   * Bug 85696 - r600g+nine: Bioshock shader failure after 7b1c0cbc90d456384b0950ad21faa3c61a6b43ff   * Bug 88219 - include/c11/threads_posix.h:197: undefined reference to `pthread_mutex_lock'   * mesa: Fix clamping to -1.0 in snorm_to_float   * glsl: Link glsl_test with pthreads library.   * i965: Respect the no_8 flag on Gen6, not just Gen7+.   * i965: Work around mysterious Gen4 GPU hangs with minimal state changes.
Rev X11:XOrg/417 Md5 88be52457b50cdcd889194bdc79b7465 2015-01-26 05:11:23 sndirsch 282755