- update to 17.1.4  * fdo#77240 - khrplatform.h not installed if EGL is disabled  * fdo#95530 - Stellaris - colored overlay of sectors doesn't render on i965  * fdo#96958 - [SKL] Improper rendering in Europa Universalis IV  * fdo#99467 - [radv] DOOM 2016 + wine. Green screen everywhere  * fdo#101071 - compiling glsl fails with undefined reference to `pthread_create'  * fdo#101252 - eglGetDisplay() is not thread safe  * fdo#101294 - radeonsi minecraft forge splash freeze since 17.1  * fdo#101451 - [G33] ES2-CTS.functional.clipping.polygon regression  * and some other fixes as usualy
Rev X11:XOrg/626 Md5 6ef87aac27c60857cee15c76fcaf8160 2017-07-03 15:15:31 sndirsch 507487